<?php

/**
 * This is the model base class for the table "historico_transferencia_vocero".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HistoricoTransferenciaVocero".
 *
 * Columns in table "historico_transferencia_vocero" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $id_vocero_emisor
 * @property integer $id_vocero_receptor
 * @property string $referencia_bancaria
 * @property integer $id_banco
 * @property integer $id_estado
 * @property string $fecha_creacion
 * @property integer $id_jornada
 * @property double $monto_transferido
 * @property integer $id_transferencia_vocero
 * @property integer $id_depositante
 *
 */
abstract class BaseHistoricoTransferenciaVocero extends GxActiveRecord {
	public $monto;
	public $nombres_apellidos_depositante;
	public $voceros;
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'historico_transferencia_vocero';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HistoricoTransferenciaVocero|HistoricoTransferenciaVoceros', $n);
	}

	public static function representingColumn() {
		return 'referencia_bancaria';
	}

	public function rules() {
		return array(
			array('id_vocero_emisor, id_vocero_receptor, referencia_bancaria, id_banco, id_estado, fecha_creacion, id_jornada, monto_transferido, id_transferencia_vocero, id_depositante', 'required'),
			array('id_vocero_emisor, id_vocero_receptor, id_banco, id_estado, id_jornada, id_transferencia_vocero, id_depositante', 'numerical', 'integerOnly'=>true),
			array('monto_transferido', 'numerical'),
			array('referencia_bancaria', 'length', 'max'=>100),
			array('id, id_vocero_emisor, id_vocero_receptor, referencia_bancaria, id_banco, id_estado, fecha_creacion, id_jornada, monto_transferido, id_transferencia_vocero, id_depositante', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_vocero_emisor' => Yii::t('app', 'Id Vocero Emisor'),
			'id_vocero_receptor' => Yii::t('app', 'Id Vocero Receptor'),
			'referencia_bancaria' => Yii::t('app', 'Referencia Bancaria'),
			'id_banco' => Yii::t('app', 'Id Banco'),
			'id_estado' => Yii::t('app', 'Id Estado'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'id_jornada' => Yii::t('app', 'Id Jornada'),
			'monto_transferido' => Yii::t('app', 'Monto Transferido'),
			'id_transferencia_vocero' => Yii::t('app', 'Id Transferencia Vocero'),
			'id_depositante' => Yii::t('app', 'Titular de la cuenta'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_vocero_emisor', $this->id_vocero_emisor);
		$criteria->compare('id_vocero_receptor', $this->id_vocero_receptor);
		$criteria->compare('referencia_bancaria', $this->referencia_bancaria, true);
		$criteria->compare('id_banco', $this->id_banco);
		$criteria->compare('id_estado', $this->id_estado);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('id_jornada', $this->id_jornada);
		$criteria->compare('monto_transferido', $this->monto_transferido);
		$criteria->compare('id_transferencia_vocero', $this->id_transferencia_vocero);
		$criteria->compare('id_depositante', $this->id_depositante);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
