<?php

/**
 * This is the model base class for the table "bancos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bancos".
 *
 * Columns in table "bancos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $nombre
 * @property string $fecha_creacion
 *
 */
abstract class BaseBancos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bancos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bancos|Bancoses', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, nombre, fecha_creacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'nombre' => Yii::t('app', 'Nombre'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}