<?php

/**
 * This is the model base class for the table "depositante".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Depositante".
 *
 * Columns in table "depositante" available as properties of the model,
 * followed by relations of table "depositante" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property integer $cedula
 * @property string $fecha_creacion
 * @property string $nombres_apellidos
 *
 * @property Tickets[] $tickets
 */
abstract class BaseDepositante extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'depositante';
	}

	public static function label($n = 1) {
		// return Yii::t('app', 'Depositante|Depositantes', $n);
		return Yii::t('app', 'Titular|Titulares', $n);
	}

	public static function representingColumn() {
		return 'nombres_apellidos';
	}

	public function rules() {
		return array(
			array('cedula, nombres_apellidos', 'required'),
			array('cedula', 'numerical', 'integerOnly'=>true),
			array('nombres_apellidos', 'length', 'max'=>100),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, cedula, fecha_creacion, nombres_apellidos', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tickets' => array(self::HAS_MANY, 'Tickets', 'id_depositante'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'cedula' => Yii::t('app', 'Cedula'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'nombres_apellidos' => Yii::t('app', 'Nombres y Apellidos'),
			'tickets' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('cedula', $this->cedula);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('nombres_apellidos', $this->nombres_apellidos, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
