<?php

/**
 * This is the model base class for the table "procesar_archivo_vocero".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProcesarArchivoVocero".
 *
 * Columns in table "procesar_archivo_vocero" available as properties of the model,
 * followed by relations of table "procesar_archivo_vocero" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $nombre
 * @property integer $id_estado
 * @property integer $id_jornada
 * @property integer $id_depositante
 * @property string $fecha_creacion
 *
 * @property BatchVocero[] $batchVoceros
 */
abstract class BaseProcesarArchivoVocero extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'procesar_archivo_vocero';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProcesarArchivoVocero|ProcesarArchivoVoceros', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('id_estado, id_jornada, id_depositante', 'numerical', 'integerOnly'=>true),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, id_estado, id_jornada, id_depositante, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, nombre, id_estado, id_jornada, id_depositante, fecha_creacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'batchVoceros' => array(self::HAS_MANY, 'BatchVocero', 'id_procesar_archivo_vocero'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'nombre' => Yii::t('app', 'Nombre'),
			'id_estado' => Yii::t('app', 'Id Estado'),
			'id_jornada' => Yii::t('app', 'Id Jornada'),
			'id_depositante' => Yii::t('app', 'Id Depositante'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'batchVoceros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('id_estado', $this->id_estado);
		$criteria->compare('id_jornada', $this->id_jornada);
		$criteria->compare('id_depositante', $this->id_depositante);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}