<?php

/**
 * This is the model base class for the table "cooperativista".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cooperativista".
 *
 * Columns in table "cooperativista" available as properties of the model,
 * followed by relations of table "cooperativista" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $nombres_apellidos
 * @property integer $cedula
 * @property string $fecha_creacion
 * @property integer $id_tipo_cooperativa
 *
 * @property TipoCooperativa $idTipoCooperativa
 */
abstract class BaseCooperativista extends GxActiveRecord {

	public $selectedIds = array();
	public $message = array();
	public $id_jornada;
	public $id_banco;
	public $id_depositante;
	public $referencia_bancaria;
	public $monto_transferido;
	public $id_vocero;
	public $nombres_apellidos_depositante;





	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cooperativista';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cooperativista|Cooperativistas', $n);
	}

	public static function representingColumn() {
		return 'nombres_apellidos';
	}

	public function rules() {
		return array(
			array('nombres_apellidos, cedula, id_tipo_cooperativa', 'required'),
			array('cedula, id_tipo_cooperativa, id_depositante, id_banco, id_vocero, id_jornada', 'numerical', 'integerOnly'=>true),
			array('monto_transferido, referencia_bancaria', 'numerical'),
			array('nombres_apellidos', 'length', 'max'=>100),
			array('cedula','unique', 'message'=>'Esta cedula ya se encuentra registrada.'),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, nombres_apellidos, cedula, fecha_creacion, id_tipo_cooperativa', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idTipoCooperativa' => array(self::BELONGS_TO, 'TipoCooperativa', 'id_tipo_cooperativa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'nombres_apellidos' => Yii::t('app', 'Nombres Apellidos'),
			'cedula' => Yii::t('app', 'Cedula'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'id_tipo_cooperativa' => null,
			'idTipoCooperativa' => null,

			'id_jornada' => Yii::t('app', 'Jornada'),
			'id_banco' => Yii::t('app', 'Banco'),
			'id_depositante' => Yii::t('app', 'Titular Cuenta'),
			'referencia_bancaria' => Yii::t('app', 'Referencia Bancaria'),
			'monto_transferido' => Yii::t('app', 'Monto Transferido'),
			'id_vocero' => Yii::t('app', 'Vocero'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('nombres_apellidos', $this->nombres_apellidos, true);
		$criteria->compare('cedula', $this->cedula);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('id_tipo_cooperativa', $this->id_tipo_cooperativa);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	public function search_generar_transferencia() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('nombres_apellidos', $this->nombres_apellidos, true);
		$criteria->compare('cedula', $this->cedula);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('id_tipo_cooperativa', $this->id_tipo_cooperativa);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}