<?php

/**
 * This is the model base class for the table "jornadarubro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jornadarubro".
 *
 * Columns in table "jornadarubro" available as properties of the model,
 * followed by relations of table "jornadarubro" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_rubro
 * @property integer $id_jornada
 *
 * @property Rubros $idRubro
 * @property Jornada $idJornada
 */
abstract class BaseJornadarubro extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'jornadarubro';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Jornadarubro|Jornadarubros', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_rubro, id_jornada', 'required'),
			array('id_rubro, id_jornada', 'numerical', 'integerOnly'=>true),
			array('id, id_rubro, id_jornada', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idRubro' => array(self::BELONGS_TO, 'Rubros', 'id_rubro'),
			'idJornada' => array(self::BELONGS_TO, 'Jornada', 'id_jornada'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_rubro' => null,
			'id_jornada' => null,
			'idRubro' => null,
			'idJornada' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_rubro', $this->id_rubro);
		$criteria->compare('id_jornada', $this->id_jornada);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}