<?php

/**
 * This is the model base class for the table "mantenimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mantenimiento".
 *
 * Columns in table "mantenimiento" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $horaInicio
 *
 */
abstract class BaseMantenimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mantenimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mantenimiento|Mantenimientos', $n);
	}

	public static function representingColumn() {
		return 'horaInicio';
	}

	public function rules() {
		return array(
			array('estatus, horaInicio', 'safe'),
			array('estatus, horaInicio', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, horaInicio', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'horaInicio' => Yii::t('app', 'Hora Inicio'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('horaInicio', $this->horaInicio, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}