<?php

/**
 * This is the model base class for the table "vocerotipovocero".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vocerotipovocero".
 *
 * Columns in table "vocerotipovocero" available as properties of the model,
 * followed by relations of table "vocerotipovocero" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_vocero
 * @property integer $id_tipo_vocero
 *
 * @property Vocero $idVocero
 * @property TipoVocero $idTipoVocero
 */
abstract class BaseVocerotipovocero extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vocerotipovocero';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vocerotipovocero|Vocerotipovoceros', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id_vocero, id_tipo_vocero', 'required'),
			array('id_vocero, id_tipo_vocero', 'numerical', 'integerOnly'=>true),
			array('id, id_vocero, id_tipo_vocero', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idVocero' => array(self::BELONGS_TO, 'Vocero', 'id_vocero'),
			'idTipoVocero' => array(self::BELONGS_TO, 'TipoVocero', 'id_tipo_vocero'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_vocero' => null,
			'id_tipo_vocero' => null,
			'idVocero' => null,
			'idTipoVocero' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_vocero', $this->id_vocero);
		$criteria->compare('id_tipo_vocero', $this->id_tipo_vocero);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}