<?php

/**
 * This is the model base class for the table "tipo_cooperativa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoCooperativa".
 *
 * Columns in table "tipo_cooperativa" available as properties of the model,
 * followed by relations of table "tipo_cooperativa" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $tipo
 * @property string $fecha_creacion
 * @property integer $id_responsable_cooperativa
 *
 * @property ResponsableCooperativa $idResponsableCooperativa
 * @property Cooperativista[] $cooperativistas
 */
abstract class BaseTipoCooperativa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_cooperativa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cooperativa|Cooperativas', $n);
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('tipo, id_responsable_cooperativa', 'required'),
			array('id_responsable_cooperativa', 'numerical', 'integerOnly'=>true),
			array('tipo', 'length', 'max'=>100),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, tipo, fecha_creacion, id_responsable_cooperativa', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idResponsableCooperativa' => array(self::BELONGS_TO, 'ResponsableCooperativa', 'id_responsable_cooperativa'),
			'cooperativistas' => array(self::HAS_MANY, 'Cooperativista', 'id_tipo_cooperativa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'tipo' => Yii::t('app', 'Cooperativa'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'id_responsable_cooperativa' => null,
			'idResponsableCooperativa' => null,
			'cooperativistas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('id_responsable_cooperativa', $this->id_responsable_cooperativa);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}