<?php

/**
 * This is the model base class for the table "tipo_vocero".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoVocero".
 *
 * Columns in table "tipo_vocero" available as properties of the model,
 * followed by relations of table "tipo_vocero" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $tipo
 * @property string $fecha_creacion
 *
 * @property Vocerotipovocero[] $vocerotipovoceros
 */
abstract class BaseTipoVocero extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_vocero';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tipo de Vocero|Tipo de Voceros', $n);
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('tipo', 'required'),
			array('tipo', 'length', 'max'=>100),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, tipo, fecha_creacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'vocerotipovoceros' => array(self::HAS_MANY, 'Vocerotipovocero', 'id_tipo_vocero'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'tipo' => Yii::t('app', 'Tipo'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'vocerotipovoceros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
