<?php

/**
 * This is the model base class for the table "vocero".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vocero".
 *
 * Columns in table "vocero" available as properties of the model,
 * followed by relations of table "vocero" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $nombres
 * @property string $apellidos
 * @property integer $cedula
 * @property string $fecha_creacion
 * @property integer $id_sede
 * @property integer $id_edificio
 * @property integer $id_piso
 *
 * @property Sede $idSede
 * @property Edificio $idEdificio
 * @property Piso $idPiso
 * @property Tickets[] $tickets
 * @property Vocerotipovocero[] $vocerotipovoceros
 */
abstract class BaseVocero extends GxActiveRecord {
	public $ids_tipo_vocero = array();

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vocero';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vocero|Voceros', $n);
	}

	public static function representingColumn() {
		return 'nombres';
	}

	public function rules() {
		return array(
			array('nombres, apellidos, cedula, ids_tipo_vocero', 'required'),
			array('cedula, id_sede, id_edificio, id_piso', 'numerical', 'integerOnly'=>true),
			array('estatus, fecha_creacion', 'safe'),
			array('ids_tipo_vocero', 'type', 'type' => 'array'),
			array('estatus, fecha_creacion, id_sede, id_edificio, id_piso', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, nombres, apellidos, cedula, fecha_creacion, id_sede, id_edificio, id_piso', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idSede' => array(self::BELONGS_TO, 'Sede', 'id_sede'),
			'idEdificio' => array(self::BELONGS_TO, 'Edificio', 'id_edificio'),
			'idPiso' => array(self::BELONGS_TO, 'Piso', 'id_piso'),
			'tickets' => array(self::HAS_MANY, 'Tickets', 'id_vocero'),
			'vocerotipovoceros' => array(self::HAS_MANY, 'Vocerotipovocero', 'id_vocero'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'nombres' => Yii::t('app', 'Nombres'),
			'apellidos' => Yii::t('app', 'Apellidos'),
			'cedula' => Yii::t('app', 'Cedula'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'ids_tipo_vocero' => Yii::t('app', 'Tipos'),
			'id_sede' => null,
			'id_edificio' => null,
			'id_piso' => null,
			'idSede' => null,
			'idEdificio' => null,
			'idPiso' => null,
			'tickets' => null,
			'vocerotipovoceros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('nombres', $this->nombres, true);
		$criteria->compare('apellidos', $this->apellidos, true);
		$criteria->compare('cedula', $this->cedula);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('id_sede', $this->id_sede);
		$criteria->compare('id_edificio', $this->id_edificio);
		$criteria->compare('id_piso', $this->id_piso);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
