<?php

/**
 * This is the model base class for the table "transferencia_cooperativa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TransferenciaCooperativa".
 *
 * Columns in table "transferencia_cooperativa" available as properties of the model,
 * followed by relations of table "transferencia_cooperativa" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_jornada
 * @property integer $id_cooperativista
 * @property integer $id_banco
 * @property string $referencia_bancaria
 * @property integer $id_estado
 * @property string $fecha_creacion
 * @property double $monto_transferido
 * @property integer $id_depositante
 * @property integer $id_vocero
 *
 * @property Jornada $idJornada
 * @property Cooperativista $idCooperativista
 * @property Bancos $idBanco
 * @property Estados $idEstado
 * @property Depositante $idDepositante
 * @property Vocero $idVocero
 */
abstract class BaseTransferenciaCooperativa extends GxActiveRecord {

	public $selectedIds = array();
	public $contar;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'transferencia_cooperativa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Transferencia Cooperativa|Transferencias Cooperativas', $n);
	}

	public static function representingColumn() {
		return 'referencia_bancaria';
	}

	public function rules() {
		return array(
			array('id_jornada, id_cooperativista, id_banco, referencia_bancaria, id_estado, fecha_creacion, monto_transferido, id_depositante, id_vocero', 'required'),
			array('id_jornada, id_cooperativista, id_banco, id_estado, id_depositante, id_vocero', 'numerical', 'integerOnly'=>true),
			array('monto_transferido', 'numerical'),
			array('referencia_bancaria', 'length', 'max'=>100),
			array('id, id_jornada, id_cooperativista, id_banco, referencia_bancaria, id_estado, fecha_creacion, monto_transferido, id_depositante, id_vocero', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idJornada' => array(self::BELONGS_TO, 'Jornada', 'id_jornada'),
			'idCooperativista' => array(self::BELONGS_TO, 'Cooperativista', 'id_cooperativista'),
			'idBanco' => array(self::BELONGS_TO, 'Bancos', 'id_banco'),
			'idEstado' => array(self::BELONGS_TO, 'Estados', 'id_estado'),
			'idDepositante' => array(self::BELONGS_TO, 'Depositante', 'id_depositante'),
			'idVocero' => array(self::BELONGS_TO, 'Vocero', 'id_vocero'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_jornada' => null,
			'id_cooperativista' => null,
			'id_banco' => null,
			'referencia_bancaria' => Yii::t('app', 'Referencia Bancaria'),
			'id_estado' => null,
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'monto_transferido' => Yii::t('app', 'Monto Transferido'),
			'id_depositante' => null,
			'id_vocero' => null,
			'idJornada' => null,
			'idCooperativista' => null,
			'idBanco' => null,
			'idEstado' => null,
			'idDepositante' => null,
			'idVocero' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_jornada', $this->id_jornada);
		$criteria->compare('id_cooperativista', $this->id_cooperativista);
		$criteria->compare('id_banco', $this->id_banco);
		$criteria->compare('referencia_bancaria', $this->referencia_bancaria, true);
		$criteria->compare('id_estado', $this->id_estado);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);
		$criteria->compare('monto_transferido', $this->monto_transferido);
		$criteria->compare('id_depositante', $this->id_depositante);
		$criteria->compare('id_vocero', $this->id_vocero);
		$criteria->addCondition('j.estatus = true');
    $criteria->join = 'INNER JOIN jornada as j ON t.id_jornada = j.id';


		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}