<?php

/**
 * This is the model base class for the table "responsable_cooperativa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResponsableCooperativa".
 *
 * Columns in table "responsable_cooperativa" available as properties of the model,
 * followed by relations of table "responsable_cooperativa" available as properties of the model.
 *
 * @property integer $id
 * @property boolean $estatus
 * @property string $nombres_apellidos
 * @property integer $cedula
 * @property string $email
 * @property integer $telefono
 * @property string $fecha_creacion
 *
 * @property TipoCooperativa[] $tipoCooperativas
 */
abstract class BaseResponsableCooperativa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'responsable_cooperativa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Responsable de Cooperativa|Responsable de Cooperativas', $n);
	}

	public static function representingColumn() {
		return 'nombres_apellidos';
	}

	public function rules() {
		return array(
			array('nombres_apellidos, cedula', 'required'),
			array('cedula, telefono', 'numerical', 'integerOnly'=>true),
			array('nombres_apellidos', 'length', 'max'=>100),
			array('email','email'),
			array('cedula','unique', 'message'=>'Esta cedula ya se encuentra registrada.'),
			array('estatus, fecha_creacion', 'safe'),
			array('estatus, email, telefono, fecha_creacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, estatus, nombres_apellidos, cedula, email, telefono, fecha_creacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tipoCooperativas' => array(self::HAS_MANY, 'TipoCooperativa', 'id_responsable_cooperativa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estatus' => Yii::t('app', 'Estatus'),
			'nombres_apellidos' => Yii::t('app', 'Nombres y Apellidos'),
			'cedula' => Yii::t('app', 'Cedula'),
			'email' => Yii::t('app', 'Email'),
			'telefono' => Yii::t('app', 'Telefono'),
			'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
			'tipoCooperativas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estatus', $this->estatus);
		$criteria->compare('nombres_apellidos', $this->nombres_apellidos, true);
		$criteria->compare('cedula', $this->cedula);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('telefono', $this->telefono);
		$criteria->compare('fecha_creacion', $this->fecha_creacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}